import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#a83300",
        "primary-container": "#cc4916",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdbd0",
        "primary-fixed-dim": "#ffb59d",
        "on-primary-fixed": "#390c00",
        "on-primary-fixed-variant": "#832600",
        background: "#fcf9f8",
        surface: "#fcf9f8",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "surface-variant": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#59413a",
        "on-background": "#1c1b1b",
        secondary: "#5e5e5b",
        "secondary-container": "#e1dfdb",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#63635f",
        "secondary-fixed": "#e4e2dd",
        "secondary-fixed-dim": "#c8c6c2",
        "on-secondary-fixed": "#1b1c19",
        "on-secondary-fixed-variant": "#474744",
        tertiary: "#5d5c56",
        "tertiary-container": "#76756e",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#feffda",
        "tertiary-fixed": "#e5e2da",
        "tertiary-fixed-dim": "#c9c6bf",
        "on-tertiary-fixed": "#1c1c17",
        "on-tertiary-fixed-variant": "#474741",
        outline: "#8d7168",
        "outline-variant": "#e5e2e1",
        "border-editorial": "#e5e2e1",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#ffb59d",
        "surface-tint": "#ac3500",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.375rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "grid-margin": "40px",
        "section-padding": "80px",
        "grid-gutter": "1px",
      },
      fontFamily: {
        sans: ["var(--font-heebo)", "Heebo", "sans-serif"],
        heading: ["var(--font-sora)", "Sora", "sans-serif"],
        display: ["var(--font-sora)", "Sora", "sans-serif"],
        sora: ["var(--font-sora)", "Sora", "sans-serif"],
        heebo: ["var(--font-heebo)", "Heebo", "sans-serif"],
      },
      fontSize: {
        "display-hero": [
          "clamp(2.75rem, 6vw, 5.5rem)",
          { lineHeight: "1.08", letterSpacing: "-0.03em", fontWeight: "600" },
        ],
        "page-title": [
          "clamp(2.25rem, 4.5vw, 4rem)",
          { lineHeight: "1.12", letterSpacing: "-0.025em", fontWeight: "600" },
        ],
        "section-title": [
          "clamp(1.75rem, 3vw, 2.75rem)",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "card-title": [
          "clamp(1.25rem, 2vw, 1.75rem)",
          { lineHeight: "1.25", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "body-lg": [
          "1.125rem",
          { lineHeight: "1.7", letterSpacing: "0em", fontWeight: "400" },
        ],
        "body-md": [
          "1rem",
          { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" },
        ],
        "body-sm": [
          "0.875rem",
          { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" },
        ],
        caption: [
          "0.8125rem",
          { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "label-caps": [
          "0.75rem",
          { lineHeight: "1", letterSpacing: "0.12em", fontWeight: "600" },
        ],
        metadata: [
          "0.8125rem",
          { lineHeight: "1.3", letterSpacing: "0.02em", fontWeight: "500" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
